apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml
configurations:
  - nameReferences.yaml
images:
  - name: controller
    newName: ghcr.io/kubecfg/kubit
    newTag: v0.0.15@sha256:db66d1fec7961f4ef00898ecdf342bd5c6ca690ec3db23fe8b8d3e8fbc79f8cc
