name: Rust

on:
  push:
    branches: ["main"]
    tags:
      - v*.*.*
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      - name: Format
        run: cargo fmt --all --check
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build
      - name: Generate
        run: cargo run -- manifests --crd-dir kustomize/crd/bases
      - name: Diff
        run: test -z "$(git status --porcelain)" || (echo 'Changes detected after generating manifests'; git status; git --no-pager diff; false)
      - name: Run unit tests
        run: cargo test --lib

  integration_tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      - uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 # v2.4.0
        with:
          cluster-name: "kubit-test-cluster-1"
      - name: Run all tests
        run: cargo test

  pack:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Depot Docker Build
        uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5 # v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Build
        if: "!github.event.pull_request.head.repo.fork"
        uses: depot/build-push-action@636daae76684e38c301daa0c5eca1c095b24e780 # v1
        with:
          project: v8n5whjnsb
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/kubecfg/kubit:latest
          load: true
      - name: Test
        if: "!github.event.pull_request.head.repo.fork"
        run: |
          docker run --rm ghcr.io/kubecfg/kubit:latest --version
      - name: Push
        uses: depot/build-push-action@636daae76684e38c301daa0c5eca1c095b24e780 # v1
        with:
          project: v8n5whjnsb
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kubecfg/kubit:latest
        if: github.event_name != 'pull_request'

  build_release:
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.image }}
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      - name: Build Release
        run: cargo build --release
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: kubit_${{ runner.os }}_${{ runner.arch }}
          path: target/release/kubit
          retention-days: 5

  create_release:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_release]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          outputFile: CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Release Binaries
        uses: actions/download-artifact@v4
        with:
          pattern: kubit_Linux_*
      - name: Move Release Binaries
        run: |
          mv kubit_Linux_X64/kubit   kubit.x86_64
          mv kubit_Linux_ARM64/kubit kubit.aarch64
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.txt
          files: |
            kubit.x86_64
            kubit.aarch64
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          generate_release_notes: true

  release:
    # Allow depot permissions to GHCR
    permissions:
      contents: read
      id-token: write
      packages: write

    needs: [pack, build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Depot Docker Build
        uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5 # v1
      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: release_image
        uses: depot/build-push-action@636daae76684e38c301daa0c5eca1c095b24e780 # v1
        with:
          project: v8n5whjnsb
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kubecfg/kubit:${{ github.ref_name }}
